module.exports = {
  Pays: require('./Pays'),
  Devise: require('./Devise'),
  TauxChange: require('./TauxChange'),
  Role: require('./Role'),
  Utilisateur: require('./Utilisateur'),
  Categorie: require('./Categorie'),
  Produit: require('./Produit'),
  Client: require('./Client'),
  Commande: require('./Commande'),
  StockMouvement: require('./StockMouvement'),
  Fournisseur: require('./Fournisseur'),
  CommandeFournisseur: require('./CommandeFournisseur'),
  CategorieDepense: require('./CategorieDepense'),
  Depense: require('./Depense'),
  CampagneMarketing: require('./CampagneMarketing'),
  MesureMarketing: require('./MesureMarketing'),
  Export: require('./Export'),
  JournalActivite: require('./JournalActivite'),
  Alerte: require('./Alerte'),
};
